development:
  adapter: postgresql
  encoding: unicode
  database: food_allergy_tracker_development

test:
  adapter: postgresql
  encoding: unicode
  database: food_allergy_tracker_test

production:
  adapter: postgresql
  encoding: unicode
  database: food_allergy_tracker_production
